/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package randomequation;

import java.awt.Color;
import java.awt.List;
import java.net.UnknownHostException;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.JLabel;





/**
 *
 * @author User
 */
public class generateEquation extends javax.swing.JFrame {

    /**
     * Creates new form generateEquation
     */
    public generateEquation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        ans1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Generate Quiz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Help");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select the answer");

        buttongroup.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttongroup.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttongroup.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttongroup.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        ans1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("check");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText(" 1)");

        jLabel6.setText("  2)");

        jLabel7.setText("   3)");

        jLabel8.setText("   4)");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("check step");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                        .addComponent(jButton4)
                                        .addGap(116, 116, 116))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel14))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ans1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ans1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jLabel6)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String[] operationSet = new String[]{"+", "-", "/", "*"};
    static Random randomGenerator = new Random();
    static String operators = "+-"; //p = parentheses pair
    static String operators2 = "x";

    public static char getRandomOperator() {
        return operators.charAt(randomGenerator.nextInt(operators.length()));

      


    }

    public static int getRandomNumber() {
        //
        //return randomGenerator.nextInt(100);
        //return (int) (Math.floor(Math.random()*-100)-100);
        return ThreadLocalRandom.current().nextInt(-10, 51);

    }

    public static int getRandomNumber1() {
        //return randomGenerator.nextInt(100);
        //return (int) (Math.floor(Math.random()*-100)-100);
        return ThreadLocalRandom.current().nextInt(100);

    }
    ArrayList numbers;

    public int getRandomNumber3(int su) {
        //return randomGenerator.nextInt(100);
        //return (int) (Math.floor(Math.random()*-100)-100);
        if (su < 0) {

            su = -(su);

        }
        numbers = new ArrayList();

        for (int i = su + 5; i <= su + 10; i++) {
            numbers.add(i);

        }
        Random rand = new Random();
        Object t = numbers.get(rand.nextInt(numbers.size()));;
        int m = ((int) t);
        numbers.remove(t);
        System.out.println("print" + m);
        return m;
        // return ThreadLocalRandom.current().nextInt(su,su+10);
    }

    public static char getRandomLetter() {
        return operators2.charAt(randomGenerator.nextInt(operators2.length()));
    }
    public static int y;

    public static String createEquation() {
        //Just for proof of concept, let's do 3 operators
        String equation = "";
        int numOfOperators = 1;
        char operator = ' ';
        Random myRand = new Random();
        for (int i = 0; i < numOfOperators; i++) {

            int random1 = getRandomNumber();
            int random2 = getRandomNumber1();
            int random3;
            do {
                random3 = getRandomNumber();
            } while (random3 == 1 || random3 == 0);

            equation += random3;
            equation += getRandomLetter();
            // String u = "(" + getRandomLetter() + ")";
            //String j = "(" + getRandomLetter() + ")";
            equation += getRandomOperator();
            //String ji = "(" + getRandomNumber() + ")";
            equation += random2 + "=" + random1;

            y = random1 * random2;

        }

        return equation;
    }

    public static String createEquation2() {
        //Just for proof of concept, let's do 3 operators
        String equation = "";
        //int numOfOperators = 1;
        // char operator = ' ';
        // Random myRand = new Random();
        //for (int i = 0; i < numOfOperators; i++) {

        int random3;
        do {
            random3 = getRandomNumber();
        } while (random3 == 1 || random3 == 0);

        equation += getRandomNumber();
        equation += getRandomOperator();
        equation += getRandomNumber1() + "=" + random3 + getRandomLetter();

        //}
        return equation;
    }

    public static String createEquation3() {
        String equation = "";
        //int numOfOperators = 1;
        //char operator = ' ';
        //Random myRand = new Random();

        int random3;
        do {
            random3 = getRandomNumber1();
        } while (random3 == 1 || random3 == 0);

        System.out.println(equation);

        equation += getRandomNumber();
        equation += getRandomOperator();
        equation += random3;
        equation += getRandomLetter() + "=" + getRandomNumber1();

        return equation;
    }

    public static String createEquation4() {
        String equation = "";
        //int numOfOperators = 1;
        //char operator = ' ';
        //Random myRand = new Random();

        int random3, random4;
        do {
            random3 = getRandomNumber1();
        } while (random3 == 1 || random3 == 0);

        do {

            random4 = getRandomNumber1();
        } while (random3 == 1 || random3 == 0);

        System.out.println(equation);
        
        
        equation += random4;
        equation += "x/";
        equation += random3;
        equation += "=" + getRandomNumber();

        return equation;
    }

    public static String createEquation5() {
        String equation = "";
        //int numOfOperators = 1;
        //char operator = ' ';
        //Random myRand = new Random();

        int random3, random4;
        do {
            random3 = getRandomNumber1();
        } while (random3 == 1 || random3 == 0);

        do {
            random4 = getRandomNumber1();
        } while (random3 == 1 || random3 == 0);

        System.out.println(equation);

        equation += random4;
        equation += "x";

        equation += "=" + getRandomNumber();
        return equation;

    }
    //
    public String finalanswer = "";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setText(" ");
        Random myRand = new Random();
        this.buttongroup.clearSelection();

        int random = 1 + myRand.nextInt(5);
// Then, once you have your Random instance:
        String equation;

        if (random == 1) {
            equation = createEquation();
            System.out.println(equation);
        } else if (random == 2) {
            equation = createEquation();
            System.out.println(equation);
        } else if (random == 3) {
          //  equation = createEquation3();
           equation = createEquation();
            System.out.println(equation);

        } else if (random == 4) {
            //equation = createEquation4();
            equation = createEquation();
            System.out.println(equation);

        } else {
             equation = createEquation();
            //equation = createEquation5();
            System.out.println(equation);

        }

        // jTextField1.setText(equation);
        String v = solving.solveEquation(equation, 'A');

        if (v.equals("Infinite solutions") || v.equals("No solution")) {

            v = solving.solveEquation(equation, 'A');
        } else {
            jTextField1.setText(equation);
            Double u = Double.valueOf(v);
            int final1 = u.intValue();
            String answer = String.valueOf(u);
            System.out.println("jjjj" + final1);
            Random rand = new Random();
            ArrayList list = new ArrayList();
            list.add(v);

            String value2 = " ";
            String value3 = " ";

            String[] solution = WrongAnswers.solveAnswers(jTextField1.getText()).split(" ");
            int j = 0;
            value2 = solution[0];
            value3 = solution[1];

            //jTextField2.setText(value2+'\n'+"mm");
            // jTextArea1.setText(String.valueOf(final1+1));
            list.add(String.valueOf(Double.valueOf(value2)));
            list.add(String.valueOf(Double.valueOf(value3)));

            int num2, num3, num4;
            //  num2=getRandomNumber3(final1);
            //list.add(String.valueOf(Double.valueOf(num2)));

            num3 = getRandomNumber3(final1 + 1);
            // jTextArea1.setText(String.valueOf(num3) + "\n" + Double.valueOf(value2) + "\n" + Double.valueOf(value3));
            list.add(String.valueOf(Double.valueOf(num3)));
            //do{ 
            //num4=getRandomNumber3(final1);
            //}while(num2==num4||num3==num4);
            //list.add(String.valueOf(Double.valueOf(num4)));

            Object yo = list.get(rand.nextInt(list.size()));
            list.remove(yo);

            Object yo1 = list.get(rand.nextInt(list.size()));
            list.remove(yo1);

            Object yo2 = list.get(rand.nextInt(list.size()));
            list.remove(yo2);

            Object yo3 = list.get(rand.nextInt(list.size()));
            list.remove(yo3);
            String ans2 = (String) yo;
            ans1.setText(ans2);
            String ans3 = (String) yo1;
            jLabel3.setText(ans3);
            String ans4 = (String) yo2;
            jLabel4.setText(ans4);
            String ans5 = (String) yo3;
            jLabel5.setText(ans5);

            if (answer.equals(ans2)) {
                // jTextField2.setText("answer is 1");
                finalanswer = "1";
            } else if (answer.equals(ans3)) {
                //jTextField2.setText("answer is 2");
                finalanswer = "2";
            } else if (answer.equals(ans4)) {
                //jTextField2.setText("answer is 3");
                finalanswer = "3";
            } else {
                //jTextField2.setText("answer is 4");
                finalanswer = "4";
            }
        }
////


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public String canswer = "";
    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (finalanswer.equals("3")) {

            canswer = "correct";
            //jTextField2.setText("answer is correct"); 
        } else {
            canswer = "incorrect";
            //jTextField2.setText("answer is incorrect");
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        if (finalanswer.equals("1")) {

            canswer = "correct";
            // jTextField2.setText("answer is correct"); 
        } else {
            canswer = "incorrect";
            //jTextField2.setText("answer is incorrect");
        }


    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (finalanswer.equals("2")) {
            canswer = "correct";
            // jTextField2.setText("answer is correct"); 
        } else {
            canswer = "incorrect";

            // jTextField2.setText("answer is incorrect");
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if (finalanswer.equals("4")) {
            canswer = "correct";
            //jTextField2.setText("answer is correct"); 
        } else {
            canswer = "incorrect";
            //jTextField2.setText("answer is incorrect");
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextArea1.setText(canswer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        getSolution getting = new getSolution();
//String v = solving.solveEquation(equation,'A');
        String value2 = " ";
        String value3 = " ";
        String value4 = " ";
        String value5 = " ";
        String[] solution = solving.solveEquation(jTextField1.getText(), 'B').split(" ");
        int j = 0;
        value2 = solution[0];
        value3 = solution[1];
        value4 = solution[2];
        value5 = solution[3];

        //jTextField2.setText(value2+'\n'+"mm");
        jTextArea1.setText(value2 + '\n'
                + value3 + '\n' + value4 + '\n' + value5);

//jTextField2.setText("insert text when you want a new line add \nThen more text....");
//jTextArea1.setText("insert text when you want a new line add \nThen more text....");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
        
         jLabel9.setText(" ");
         jLabel10.setText(" ");
          jLabel11.setText(" ");
           jLabel12.setText(" ");
             jLabel13.setText(" ");
              jLabel14.setText(" ");
        
        
        
        String value2 = " ";
        String value3 = " ";
        String value4 = " ";
        String value5 = " ";
        String[] solution = solving.solveEquation(jTextField1.getText(), 'B').split(" ");
        
        int j = 0;
        value2 = solution[0];
        value3 = solution[1];
        value4 = solution[2];
        value5 = solution[3];
        
     
        
        String valu2 = " ";
        String valu3 = " ";
        String valu4 = " ";
        String valu5 = " ";
         String valu6 = " ";
          String valu7=" ";
        //int j = 0;
        
        
         String[] solution3=new String[10];
        int itemCount = jTextArea2.getText().split("\\r?\\n").length;
      // frame.add(new JLabel("<html>Text color: <font color='red'>red</font></html>"));
        solution3 = jTextArea2.getText().split("\\r?\\n");
        
         String[] solution2=new String[itemCount];
         System.out.println(itemCount);
//       solution2[5]=" ";
        
         solution2[0]=solution3[0].replaceAll("\\s+", "");
         solution2[1]=solution3[1].replaceAll("\\s+", "");
         solution2[2]=solution3[2].replaceAll("\\s+", "");
         solution2[3]=solution3[3].replaceAll("\\s+", "");
         solution2[4]=solution3[4].replaceAll("\\s+", "");
         
         
         System.out.println(solution2[0]);
        System.out.println(solution2[1]);
        System.out.println(solution2[2]);
        System.out.println(solution2[3]);
        System.out.println(solution2[4]);
    
        valu2 = solution2[0];
        valu3 = solution2[1];
        valu4 = solution2[2];
        valu5 = solution2[3];
    
        valu6=solution2[4];
         
         jLabel9.setText(valu2);
         jLabel10.setText(valu3);
          jLabel11.setText(valu4);
           jLabel12.setText(valu5);
             jLabel13.setText(valu6);
               
         
         if(itemCount==6)
         {
          solution2[5]=solution3[5].replaceAll("\\s+", "");
             valu7=solution2[5];
               System.out.println(solution2[5]);
                jLabel14.setText(valu7);
         
         }
        
         String[] elements = null;
       String solutionSteps;
        try {
           solutionSteps=solutionTree.solveEquation(jTextField1.getText(),'A' ,solution2) ;
          elements = solutionSteps.split(" ");
           //System.out.println("lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll"+  solutionSteps);
        } catch (UnknownHostException ex) {
            Logger.getLogger(generateEquation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
                
                
                
                
    String v2 = elements[0];
    String v3 = elements[1];
    String v4 = elements[2];
    String v5 = elements[3];
    String v6=elements[4];
    if(itemCount==6){
    
    String v7=elements[5];
    }
                
                
        if(v2.equals(valu2))
        {
        
         
            
   
         if(v3.equals(valu3))
         {
 
            
             
             if(v4.equals(valu4))
             {
             
             if(v5.equals(valu5))
             {
             
             
              jTextArea2.setText("correct");
             
             }
             
              else
              jLabel12.setForeground(Color.red);
             
             
             
    
             
          }
              else
              jLabel11.setForeground(Color.red);
              
             
             
         
         }
          else
             jLabel10.setForeground(Color.red);
             
         
        }
           
        else
             System.out.println("incorrect"); 

        
        
        
        
  
}catch(ArrayIndexOutOfBoundsException  e){
jTextArea2.setText("enter more steps");
}  
        
        
       
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generateEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generateEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generateEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generateEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generateEquation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ans1;
    private javax.swing.ButtonGroup buttongroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
